#!/usr/bin/env python
# Copyright 2026-present Kensho Technologies, LLC.
"""
Generate script_data.py (Python) and script_data.rs (Rust) from Unicode Scripts.txt.

Source: https://www.unicode.org/Public/17.0.0/ucd/Scripts.txt

Usage:
    python unicode_data/generate_script_data.py

Reads:  unicode_data/Scripts.txt  (Unicode 17.0)
Writes: python/boundlessbpe/script_data.py
        src/script_data.rs
        unicode_data/script_stats.txt
"""

import os
import sys
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

SCRIPTS_URL = "https://www.unicode.org/Public/17.0.0/ucd/Scripts.txt"
SCRIPTS_TXT = os.path.join(SCRIPT_DIR, "Scripts.txt")
STATS_OUT = os.path.join(SCRIPT_DIR, "script_stats.txt")
PY_OUT = os.path.join(REPO_ROOT, "python", "boundlessbpe", "script_data.py")
RS_OUT = os.path.join(REPO_ROOT, "src", "script_data.rs")


def parse_scripts_txt(path: str) -> list[tuple[int, int, str]]:
    """Parse Scripts.txt into (start, end, script_name) ranges."""
    ranges: list[tuple[int, int, str]] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Format: "XXXX..YYYY ; Script_Name # ..." or "XXXX ; Script_Name # ..."
            comment_idx = line.find("#")
            if comment_idx >= 0:
                line = line[:comment_idx].strip()
            parts = line.split(";")
            if len(parts) != 2:
                continue
            codepoints = parts[0].strip()
            script = parts[1].strip()
            if ".." in codepoints:
                start_s, end_s = codepoints.split("..")
                start = int(start_s, 16)
                end = int(end_s, 16)
            else:
                start = int(codepoints, 16)
                end = start
            ranges.append((start, end, script))
    ranges.sort(key=lambda r: r[0])
    return ranges


def build_script_index(ranges: list[tuple[int, int, str]]) -> tuple[list[str], dict[str, int]]:
    """Build a mapping from script name to u8 index. Index 0 is always 'Unknown'."""
    seen: dict[str, int] = {"Unknown": 0}
    for _, _, script in ranges:
        if script not in seen:
            seen[script] = len(seen)
    if len(seen) > 256:
        raise ValueError(f"Too many scripts ({len(seen)}) to fit in a byte")
    names = [""] * len(seen)
    for name, idx in seen.items():
        names[idx] = name
    return names, seen


def write_stats(ranges: list[tuple[int, int, str]], path: str) -> None:
    """Write statistics about all scripts to a file and print summary to stdout."""
    script_counts: dict[str, int] = defaultdict(int)
    for start, end, script in ranges:
        script_counts[script] += end - start + 1

    total_assigned = sum(script_counts.values())
    unassigned = 0x110000 - total_assigned

    # Write full stats to file
    lines: list[str] = []
    lines.append(f"Unicode script statistics (Scripts.txt, Unicode 17.0)")
    lines.append(f"Source: {SCRIPTS_URL}")
    lines.append(f"")
    lines.append(f"Number of ranges: {len(ranges)}")
    lines.append(f"Number of distinct scripts: {len(script_counts)}")
    lines.append(f"Total assigned code points: {total_assigned:,}")
    lines.append(f"Unassigned (mapped to Unknown): {unassigned:,}")
    lines.append(f"")
    lines.append(f"All scripts by code point count:")
    lines.append(f"")
    for script, count in sorted(script_counts.items(), key=lambda x: -x[1]):
        lines.append(f"  {script:30s} {count:>8,}")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path} ({len(script_counts)} scripts)")

    # Print summary to stdout
    print(f"Number of ranges: {len(ranges)}")
    print(f"Number of distinct scripts: {len(script_counts)}")
    print(f"Total assigned code points: {total_assigned:,}")
    print(f"Unassigned (mapped to Unknown): {unassigned:,}")


def generate_python(
    ranges: list[tuple[int, int, str]],
    script_names: list[str],
    script_to_idx: dict[str, int],
    path: str,
) -> None:
    """Generate python/boundlessbpe/script_data.py."""
    lines: list[str] = []
    lines.append('"""')
    lines.append("Unicode script data generated from Scripts.txt (Unicode 17.0).")
    lines.append(f"Source: {SCRIPTS_URL}")
    lines.append("")
    lines.append("DO NOT EDIT - generated by unicode_data/generate_script_data.py")
    lines.append('"""')
    lines.append("")
    lines.append("")
    # Named constants for the three scripts checked by name in pretokenize
    lines.append(f"UNKNOWN = {script_to_idx['Unknown']}")
    lines.append(f"COMMON = {script_to_idx['Common']}")
    lines.append(f"INHERITED = {script_to_idx['Inherited']}")
    lines.append("")
    lines.append(f"NUM_SCRIPTS = {len(script_names)}")
    lines.append("")
    lines.append(f"# {len(script_names)} script names indexed by u8 value (0 = Unknown)")
    lines.append("SCRIPT_NAMES: list[str] = [")
    for name in script_names:
        lines.append(f"    {name!r},")
    lines.append("]")
    lines.append("")
    lines.append("SCRIPT_NAME_TO_INDEX: dict[str, int] = {")
    for name, idx in sorted(script_to_idx.items(), key=lambda x: x[1]):
        lines.append(f"    {name!r}: {idx},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("# (start, end, script_index) - sorted by start code point")
    lines.append("SCRIPT_RANGES: list[tuple[int, int, int]] = [")
    for start, end, script in ranges:
        idx = script_to_idx[script]
        lines.append(f"    (0x{start:04X}, 0x{end:04X}, {idx}),  # {script}")
    lines.append("]")
    lines.append("")
    lines.append("")
    lines.append("def init_script_array() -> bytearray:")
    lines.append('    """Build a full script lookup bytearray of length 0x110000.')
    lines.append("")
    lines.append("    Each byte is an index into SCRIPT_NAMES.")
    lines.append("    Unassigned code points default to 0 (Unknown).")
    lines.append('    """')
    lines.append("    arr = bytearray(0x110000)")
    lines.append("    for start, end, idx in SCRIPT_RANGES:")
    lines.append("        for cp in range(start, end + 1):")
    lines.append("            arr[cp] = idx")
    lines.append("    return arr")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {path} ({len(ranges)} ranges, {len(script_names)} scripts)")


def generate_rust(
    ranges: list[tuple[int, int, str]],
    script_names: list[str],
    script_to_idx: dict[str, int],
    path: str,
) -> None:
    """Generate src/script_data.rs."""
    lines: list[str] = []
    lines.append("// Unicode script data generated from Scripts.txt (Unicode 17.0).")
    lines.append(f"// Source: {SCRIPTS_URL}")
    lines.append("//")
    lines.append("// DO NOT EDIT - generated by unicode_data/generate_script_data.py")
    lines.append("")
    lines.append("use std::sync::OnceLock;")
    lines.append("")
    # Named constants
    lines.append(f"pub const UNKNOWN: u8 = {script_to_idx['Unknown']};")
    lines.append(f"pub const COMMON: u8 = {script_to_idx['Common']};")
    lines.append(f"pub const INHERITED: u8 = {script_to_idx['Inherited']};")
    lines.append("")
    lines.append(f"/// {len(script_names)} script names indexed by u8 value (0 = Unknown).")
    lines.append(
        f"pub static SCRIPT_NAMES: [&str; {len(script_names)}] = ["
    )
    for name in script_names:
        lines.append(f'    "{name}",')
    lines.append("];")
    lines.append("")
    lines.append("/// (start, end_inclusive, script_index)")
    lines.append(
        f"static SCRIPT_RANGES: [(u32, u32, u8); {len(ranges)}] = ["
    )
    for start, end, script in ranges:
        idx = script_to_idx[script]
        lines.append(f"    (0x{start:04X}, 0x{end:04X}, {idx}), // {script}")
    lines.append("];")
    lines.append("")
    lines.append("static SCRIPT_ARRAY: OnceLock<Vec<u8>> = OnceLock::new();")
    lines.append("")
    lines.append("fn build_script_array() -> Vec<u8> {")
    lines.append("    let mut arr = vec![0u8; 0x110000];")
    lines.append("    for &(start, end, idx) in SCRIPT_RANGES.iter() {")
    lines.append("        for cp in start..=end {")
    lines.append("            arr[cp as usize] = idx;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    arr")
    lines.append("}")
    lines.append("")
    lines.append("/// Look up the Unicode script index for a character (O(1) byte-array lookup).")
    lines.append("pub fn script_of(ch: char) -> u8 {")
    lines.append("    let arr = SCRIPT_ARRAY.get_or_init(build_script_array);")
    lines.append("    arr[ch as u32 as usize]")
    lines.append("}")
    lines.append("")
    lines.append("/// Convert a script name to its u8 index.")
    lines.append("pub fn script_name_to_index(name: &str) -> Option<u8> {")
    lines.append("    SCRIPT_NAMES.iter().position(|&n| n == name).map(|i| i as u8)")
    lines.append("}")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {path} ({len(ranges)} ranges, {len(script_names)} scripts)")


def main() -> None:
    if not os.path.exists(SCRIPTS_TXT):
        print(f"ERROR: {SCRIPTS_TXT} not found", file=sys.stderr)
        sys.exit(1)

    ranges = parse_scripts_txt(SCRIPTS_TXT)
    script_names, script_to_idx = build_script_index(ranges)
    write_stats(ranges, STATS_OUT)
    print()
    generate_python(ranges, script_names, script_to_idx, PY_OUT)
    generate_rust(ranges, script_names, script_to_idx, RS_OUT)
    print(f"\n{len(script_names)} scripts fit in u8 (max index {len(script_names) - 1}).")
    print("Done.")


if __name__ == "__main__":
    main()
